---
title: "Emperyalizmin Ülkelerin Gelişimine ve Ekonomisine Etkisi"
author: 
  - Hasan Umut Avcı[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 20080258, [Github Repo](https://github.com/umutavci4/arasinav)



# Giriş
Emperyalizm, yayılmacılık yoluyla kurulan, gücün elde tutulup başka bir ulus üzerinde kurulan sert hegemonyaya verilen addır. Hegemonya kuran güç, kendi çıkarlarını ön planda tutarak bir başka ulus üzerinde sömürgeci politikalar uygular. Bunun neticesinde de sömüren güç ekonomik de dahil olmak üzere birtakım kazançlar elde ederken sömürülen taraf için ise aynı şeyi söylemek genelde mümkün olmaz. Harcard Datasets'ten bulmuş olduğum 15 değişkenli ve 52 gözlemli veri seti, içerisinde belli başlı ülkelerin gayri safi milli hasılasını, nüfusuna göre dini inanışları, yıllar içindeki gelişim puanları gibi değişkenleri barındırmaktadır. Bu veri setini seçmemin sebebi emperyalizmin hakim olduğu ülkelerin sömürgeleşmesinin ardından ortaya çıkan ekonomik tabloyu gözler önüne sermektir.
Sömürgecilik emperyalizmin “önsözü” olarak yorumlanabilir; bir başka
deyişle emperyalizmin altyapısını oluşturmaktadır. Nitekim 19. yüzyılın sonlarına
doğru emperyalizm sömürgeci politikaları etkin olarak kullanmıştır. Aslında yeni
dünyanın keşfi ile birlikte 16. yüzyılda sömürgecilik ortaya çıkmış, giderek
yaygınlaşmaya başlamıştır. Önceleri siyasi, askeri, dini hatta prestij nedeniyle ivme
kazanan sömürgecilik giderek ekonomik temele sahip olmuştur. 17. yüzyıldaki köle
ticareti, sömürgelerdeki plantasyonlarda kölelerin çalıştırılmaları, sömürgelerin
Avrupa ülkeleri için büyük bir kar ve birikim kaynağı olmasını sağlamıştır. Birinci
ve İkinci Sanayi Devriminin yol açtığı sınai faaliyetlerdeki hızlı artış; ucuz
hammadde ve mamul mallara pazar bulma ihtiyacını doğurmuş ve sömürgeci
politikaların yoğunluğu artırılmıştır. [@sonmezsonmez]

## Çalışmanın Amacı
Bu çalışmada emperyalizmin boyunduruğu altında yaşamış ve emperyalist emellerle hareket etmiş olan ülkelerin zaman içerisindeki gelişimlerini, ekonomilerini konu alan veri setlerini inceledik. Emperyalizmin bir ülke üzerindeki olumlu olumsuz etkilerine, gayri safi yurt içi hasılanın emperyalizmle doğrudan bir bağı olup olmadığına, ekonomik gelişmelerin emperyalizmle olan bağına veri setlerini analiz ederek istatistiki verilere derleyeceğiz.

## Literatür
XVI. yüzyılda başlayan ve XIX. yüzyılda kemale eren Avrupa’nın dönüşümü tüm dünyanın kaderini ve geleceğini etkileyen bir şekil almıştır. Emperyalizm çağı XIX. yüzyılda Avrupa’ya modern görünümünü veren iktisadî, siyasî, insanî dönüşümler üzerinde yükselen bir dönem olarak ortaya çıktı. Bu dönüşümler Avrupalı devletlerin olduğu kadar bireylerin ve toplumsal yapıları davranışlarına da yön veren bir olgu olarak emperyalizmi ortaya çıkardı. Emperyalizm ile birlikte yayılma ve şiddet belirgin bir şekilde artmış vedünyada hızlı bir ekonomik, siyasal, kültürel ve sosyal değişim yaşanmıştır. Böylece emperyalizm bir sistem olarak son derece etkin ve etkili bir değişim dinamiği olmuştur. [@iusosyoloji4737]
Az gelişmiş ülkelerin dış fonlara yönelik mevcut ve gelecekteki gereksinimlerinin kesin miktarları ve oranları burada bizi ilgilendirmez. Bununla birlikte, daha az somut olsa da bazı daha büyük faktörlerden uygun şekilde bahsedilebilir. Birincisi ve en önemlisi, dünyadaki sermaye kıtlığıdır. Doğu Afrika Kraliyet Komisyonu'nun 1955'te doğru bir şekilde çıkardığı gibi, "Afrika'nın sermayeye, sermayenin Afrika'ya ihtiyacından daha fazla ihtiyacı var." "Kapılar açılırsa, herhangi bir az gelişmiş ülkeyi tutmayı bekleyen büyük bir yabancı sermaye seli yoktur." Sterlin Bölgesi, Orta Afrika Federasyonu için, 12 İngiliz Milletler Topluluğu ülkelesi ve sömürge imparatorlukları "net sermaye ithalatının ana tedarikçisi" olmaya devam edebilir. Bununla birlikte, savaş sonrası dönemde Birleşik Devletler, dünyanın önde gelen alacaklı ülkesi olarak Büyük Britanya'nın yerini almıştır. Amerika Birleşik Devletleri dünyanın önde gelen özel sermaye ihracatçısı haline geldi. Ancak savaş sonrası yıllarda bu özel sermaye ihracatının gerçek düzeyi, bir şekilde az da olsa, 1920'lerin zirve yıllarında ABD'nin sermaye ihracından daha düşük olmuştur. 1956'da Amerika Birleşik Devletleri'nden büyük ölçüde artan özel sermaye çıkışı bile, satın alma gücü açısından, 1928'de ulaşılan tüm zamanların zirvesinin altında kaldı ve temsil etti: Tabii ki, ulusal üretimin ve ABD'nin uluslararası ticaret işlemlerinin çok daha küçük bir kısmı. Ayrıca, özel fonlardaki bu artan hareketin açık farkla büyük bir kısmı, Kanada'daki yatırımlardaki önemli artış, Trinidad'da bir İngiliz petrol şirketinin satın alınması ve Venezuela'da yeni petrol imtiyazlarının alınmasıyla açıklanmıştı. 1920'lerin koşullarında oldukça cazip yatırım fırsatları sağlayacak olan dünyanın birçok yerindeki yatırımlara karşı özel yatırımcılar tarafından bir "grev" yaklaşan bir şeydi. Profesör Cairncross tarafından yapılan etkileyici çalışma, Amerika Birleşik Devletleri, Kanada ve Avustralya'nın hızlı büyümesini gören Birinci Dünya Savaşı'ndan önceki uzun nesilde kronik bir sterlin sıkıntısı olmadığını gösteriyor. Bununla birlikte, bugün kronik bir dolar kıtlığı var, öyle ki, Profesör Cairncross'un belirttiği gibi, "Amerikan kaynaklarının aynı oranı, İngiltere'nin 1913'te (çok daha küçük bir ulusal gelirden) ayırdığı kadar yabancı yatırıma ayrılsaydı, akış yatırımın otuz kat daha büyük olması gerekir. Tüm Marshall Planı yılda iki kez yapılmalıdır." [@britnell44]
"Emperyalizm"in ve onun farklı evreleriyle ilişkili dinamik özelliklerin Marksist analizi, aşağıdaki ana nedenlerden dolayı sistematik bir bilimsel yaklaşımı temsil eder:
(1) Üretim güçlerinin ve ilişkilerinin gelişiminin her aşamasının işleyişinde sınıf güçlerinin ortaya çıkışına, hizalanmasına ve çelişkisine ve bir aşamadan diğerine niteliksel sıçramaya yaklaşımı bakımından tarihseldir; (2) Diyalektiktir, yani Marksizm toplumsal, ekonomik ve politik değişimi çelişki merceğinden, yani egemen (yani, kaynakları kontrol eden) ve ezilen (yani, emek sağlayan) sınıflar arasındaki artan çatışma, kısa ve orta vadede evrimsel araçlarla ayarlanabilecek, ancak uygun çözümü ve karşıt sınıflar arasındaki iktidar ilişkilerinde buna bağlı değişiklikler için devrimci araçlar gerektirecek ilişkiler; (3) Belirli sosyal çevrelerdeki gelişmeleri daha geniş bir küresel veya uluslararası bağlama yerleştirmeye çalışmak anlamında karşılaştırmalıdır; (4) Ampirist olmanın aksine ampiriktir; başka bir deyişle, Marksist yöntem, bu tür materyallerin öğrencilerin teoriyi detaylandırmasına ne ölçüde yardımcı olduğunu incelemek ve çelişkili görünen verileri incelemek için veri toplamaya ve somut durumların incelenmesine büyük önem verir. "sınıf ilişkilerinin" yorumunun sürekli bir eleştirisini sağlama görüşüyle teorinin zerresi. Marksist yöntem, "kaba ampirizme" veya "ölçülebilecek herhangi bir şeyin ölçülmesine" veya "ölçmek için ölçmeye" yer olmaması anlamında ampirist değildir; ne de "olamayacak olan" şeklindeki bilim dışı görüşe tahammül edemez.
ölçülen, sosyal, politik ve ekonomik analiz ve açıklamaların üretilmesinde dikkate alınmaya değmez; (5) Disiplinler arasıdır, tarihsel temelli dinamik analizlerin işaret edebileceği genel sonuçlara dayanmak için bir dizi farklı sosyal bilimi getirir.[@sathyamurthy777]
Marksist tanımdan farklı olarak, bu analizde kullanılan emperyalizm kavramı, ekonomik motivasyonların ve ekonomik kontrol yöntemlerinin ötesine geçecektir. Çünkü emperyalizm, bir devletin gücünün herhangi bir yönünü, başka bir devletin genel gelişimini veya idaresini, hangi amaç ve yöntemle olursa olsun kontrol etmek ve yönlendirmek için kullandığı her durumda var olur. Bu tür bir kontrolün nedenleri hanedan veya bürokratik saiklerde, askeri mülahazalarda, kültürel, dinsel veya ekonomik baskılarda bulunabilir. Emperyalist kontrol, ilhak, himaye bölgelerinin kurulması yoluyla veya yalnızca ekonomik nüfuz ve devlet yaşamının kilit alanları -dış ilişkiler, savunma, merkez bankacılığı, ekonomik planlama veya vergilendirme- üzerinde yabancı kontrolü yoluyla işleyebilir. Yabancı kontrolünün zorunlu olarak mağdur devletin sömürüsüyle sonuçlanması gerektiğinin varsayılmasına gerek yoktur; ancak mağdur devlete sağlanan faydaların tesadüfi olduğu anlaşılmalıdır, çünkü
  emperyalist devletin kesinlikle kendi çıkarları doğrultusunda hareket ettiği varsayılır.
  Böyle bir emperyalist model oluşturmak için üç faktör gereklidir: (1)
  gerekli kontrolü uygulama gücü, (2) tanımlanabilir bir varlığın varlığı
  bu kontrolün dayatılmasının nedeni ve (3)
  emperyalizmi, daha zayıf bir devletin işlerine geçici müdahaleden ayırmak için yeterince uzun bir süre için kontrol modeli. [@ernest222]




\newpage
# Kaynakça {#references}
<div id="refs"></div>

